ALTER TABLE public.jobs ALTER COLUMN "date" DROP NOT NULL;
ALTER TABLE public.jobs ALTER COLUMN "type" DROP NOT NULL;
ALTER TABLE public.jobs ALTER COLUMN "description" DROP NOT NULL;
ALTER TABLE public.jobs ALTER COLUMN "amount" DROP NOT NULL;
ALTER TABLE public.jobs ALTER COLUMN "hours" DROP NOT NULL;
ALTER TABLE public.jobs ALTER COLUMN "notes" DROP NOT NULL; 